spring:
  port: ${SPRING_PORT}
  application:
    name: BE

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 15

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${SECRET_KEY}
    # 토큰 유효기간: 1시간
    expiryTime: 3600000

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        base-url: ${OPENAI_BASE_URL}
        options:
          model: ${OPENAI_MODEL}
          temperature: ${OPENAI_TEMPERATURE}
          max-tokens: ${OPENAI_MAX_TOKENS}
        embedding:
          api-key: ${OPENAI_API_KEY}

        completions-path: "/chat/completions"


# 요청 응답에 모두 한글 인코딩 강제 적용
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


