spring:
  port: ${SPRING_PORT}
  application:
    name: BE
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 15

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: ${SECRET_KEY}
    # 토큰 유효기간: 1시간
    expiryTime: 3600000 

# 요청 응답에 모두 한글 인코딩 강제 적용
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

